spring.application.name=schedule-api

spring.datasource.url = jdbc:postgresql://localhost:5432/schedule-api
spring.datasource.username=postgres
spring.datasource.password=5432
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true